export const TECH_STACK = [
  { id: 'react', name: 'React' },
  { id: 'nextjs', name: 'Next.js' },
  { id: 'typescript', name: 'Typescript' },
  { id: 'javascript', name: 'Javascript' },
  { id: 'redux', name: 'Redux' },
  { id: 'reactQuery', name: 'ReactQuery' },
  { id: 'git', name: 'Git' },
  { id: 'tailwind', name: 'Tailwind' },
  { id: 'styledComponents', name: 'StyledComponents' },
  { id: 'emotion', name: 'Emotion' },

  // { alt: 'React', src: '/assets/images/react.png' },
  // { alt: 'Next.js', src: '/assets/images/next.png' },
  // { alt: 'Typescript', src: '/assets/images/typescript.png' },
  // { alt: 'Javascript', src: '/assets/images/javascript.png' },
  // { alt: 'Redux', src: '/assets/images/redux.png' },
  // { alt: 'React Query', src: '/assets/images/reactQuery.png' },
  // // { alt: 'recoil', src: '/assets/images/recoil.png' },
  // { alt: 'Git', src: '/assets/images/git.png' },
  // { alt: 'Tailwind', src: '/assets/images/tailwind.png' },
  // { alt: 'Styled-Components', src: '/assets/images/tailwind.png' },
  // { alt: 'Emotion', src: '/assets/images/tailwind.png' },
  // { alt: 'emotion', src: '/assets/images/emotion.png' },
]
