import { Montserrat } from '@next/font/google'

import Header from '@/components/organisms/header'
import StyledComponentsRegistry from '@/lib/registry'
import '@/styles/global.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StyledComponentsRegistry>
      <html lang="en" className={montserrat.className}>
        <body>
          <main className="h-screen w-full">
            <Header />
          
              <div className="px-8 foldable:px-16 laptop:px-32">{children}</div>
       
          </main>
        </body>
      </html>
    </StyledComponentsRegistry>
  )
}
